// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEHnDSAq8uw6IqvQImm73uvWVoWHZrhCQ',
    appId: '1:747934686752:web:b24a39717ff213af95e645',
    messagingSenderId: '747934686752',
    projectId: 'testtask-a8c40',
    authDomain: 'testtask-a8c40.firebaseapp.com',
    storageBucket: 'testtask-a8c40.firebasestorage.app',
    measurementId: 'G-MKN3MLEXB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-n8ng2j7zdDIOpI_19DIaQY0oyc4wRws',
    appId: '1:747934686752:android:5b834b69b378fd4595e645',
    messagingSenderId: '747934686752',
    projectId: 'testtask-a8c40',
    storageBucket: 'testtask-a8c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXRFKWQwOQIJoLQ64tj5XYdfMR8Zo-RY',
    appId: '1:747934686752:ios:819e2b766213a64695e645',
    messagingSenderId: '747934686752',
    projectId: 'testtask-a8c40',
    storageBucket: 'testtask-a8c40.firebasestorage.app',
    iosBundleId: 'com.example.rapiddTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfXRFKWQwOQIJoLQ64tj5XYdfMR8Zo-RY',
    appId: '1:747934686752:ios:819e2b766213a64695e645',
    messagingSenderId: '747934686752',
    projectId: 'testtask-a8c40',
    storageBucket: 'testtask-a8c40.firebasestorage.app',
    iosBundleId: 'com.example.rapiddTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEHnDSAq8uw6IqvQImm73uvWVoWHZrhCQ',
    appId: '1:747934686752:web:243288b9bb2f5d3d95e645',
    messagingSenderId: '747934686752',
    projectId: 'testtask-a8c40',
    authDomain: 'testtask-a8c40.firebaseapp.com',
    storageBucket: 'testtask-a8c40.firebasestorage.app',
    measurementId: 'G-QBFKQ0MKCH',
  );
}
